# Generated by Django 5.0.6 on 2024-10-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0003_remove_student_password2_student_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
