# Generated by Django 5.0.6 on 2024-10-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0005_course_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='sim.course'),
        ),
    ]
