# Generated by Django 5.0.6 on 2024-10-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0006_student_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
