# Generated by Django 5.0.6 on 2024-10-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0008_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
