# Generated by Django 5.0.6 on 2024-10-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0009_enrollment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='rating',
        ),
    ]
