# Generated by Django 5.0.6 on 2024-10-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0011_enrollment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
